import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>{{projectName}}</title>
        <meta name="description" content="Generated by Next.js Pages Router" />
      </Head>
      <main style={{ padding: "2rem", fontFamily: "sans-serif" }}>
        <h1>Welcome to {{projectName}} 🎉</h1>
        <p>This is a Next.js project using the <strong>Pages Router</strong>.</p>
      </main>
    </>
  );
}